### ISSUE TITLE
The instance member 'runtimeType' can't be accessed in an initializer. 

### ISSUE THREAD

**Issue by zouxianbincc** [Hu-Wentao/get_state#1]
../lib/src/abs.dart:24:15: Error: Getter not found: 'runtimeType'.
            '$runtimeType<$VM>是一个View,它必须添加ViewModel泛型!'),
              ^^^^^^^^^^^

**Comment by Hu-Wentao** [comment]
这是新SDK在编译前无法进行runtimeType检查导致的, 建议使用最新版本的package, 或者进入源码, 将该行代码注释.
